import fs from 'node:fs';
import path from 'node:path';

// GitHub Pages has no server-side routing: it serves a file or it 404s. A client-side
// router alone means /articles/<slug> works when you click to it and breaks when you
// paste it into a fresh tab. So every real URL needs a real file on disk.
//
// This writes a copy of the built index.html at each route, differing only in <title>
// so tabs, search results, and link previews show the article rather than the site name.

const distDir = process.env.DIST_DIR || path.join(process.cwd(), 'dist');
const articlesFile = path.join(process.cwd(), 'src/data/articles.ts');

const template = fs.readFileSync(path.join(distDir, 'index.html'), 'utf8');

// articles.ts is generated by sync-articles.js as a TS module; the array literal in it
// is plain JSON, so read it without pulling in a TypeScript toolchain just to parse.
const source = fs.readFileSync(articlesFile, 'utf8');
const marker = 'export const articles: Article[] = ';
const jsonStart = source.indexOf(marker) + marker.length;
const jsonEnd = source.lastIndexOf(']');
const articles = JSON.parse(source.slice(jsonStart, jsonEnd + 1));

const escapeHtml = (value) =>
  value.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

const writeRoute = (routePath, title) => {
  const outDir = path.join(distDir, routePath);
  fs.mkdirSync(outDir, { recursive: true });
  const html = template.replace(/<title>[\s\S]*?<\/title>/, `<title>${escapeHtml(title)}</title>`);
  fs.writeFileSync(path.join(outDir, 'index.html'), html);
};

let routes = 0;

// Language is part of the path (/articles/... and /cn/articles/...), so both need a
// real file or a pasted Chinese URL 404s on a cold load.
writeRoute('cn', 'Sean Blog');

for (const article of articles) {
  writeRoute(path.join('articles', article.slug), article.titleEn);
  writeRoute(path.join('cn', 'articles', article.slug), article.titleZh || article.titleEn);
  routes += 2;
}

// Anything else — a typo, a deleted slug — still boots the app rather than showing
// GitHub's default 404 page.
fs.writeFileSync(path.join(distDir, '404.html'), template);

console.log(
  `Prerendered ${routes} article route(s) across /articles and /cn/articles, plus a 404 fallback.`,
);
